### PR TITLE
add back Cortex.loom test file

### PR DESCRIPTION
**Pull request by imyiningliu**

### CODE REVIEW

**Comment by jeff-regier** [comment]
How did the tests pass without it?

**Comment by imyiningliu** [comment]
I passed in the `url` in `test_scvi.py`. It downloads from the web and puts the raw dataset file in `tests/data/` as `Cortex.loom` :(

**Comment by jeff-regier** [comment]
Got it. You'll change it to use the test data for the tests?

**Comment by imyiningliu** [comment]
Yup! I added back the `Cortex.loom` in `tests/data/` so we wouldn't download the raw data when we run unit test. Sorry for accidentally removing it from the repo before.

**Comment by jeff-regier** [comment]
Oh I see. It's no problem at all...I was just trying to understand the change.

**Pull request merged**
