### PR TITLE
Make removal of empty cells more memory efficient.

### PR DESCRIPTION
**Pull request by JohnReid**
I found the method of removing empty cells from datasets quite memory inefficient. This pull request contains a fix and a test case that shows the behaviour is the same.

### CODE REVIEW

**Comment by JohnReid** [comment]
The failing checks above do not seem related to this PR.

**Comment by jeff-regier** [comment]
Hi John, Thanks for the contribution! This looks like a nice improvement.

I seems like the CI check failing actually is due to this PR:
```
$ flake8
./tests/test_remove_empty.py:17:7: E111 indentation is not a multiple of four
./tests/test_remove_empty.py:18:7: E111 indentation is not a multiple of four
./tests/test_remove_empty.py:19:7: E111 indentation is not a multiple of four
./tests/test_remove_empty.py:20:11: E111 indentation is not a multiple of four
./tests/test_remove_empty.py:21:15: E111 indentation is not a multiple of four
./tests/test_remove_empty.py:22:19: E111 indentation is not a multiple of four
./tests/test_remove_empty.py:23:7: E111 indentation is not a multiple of four
./tests/test_remove_empty.py:35:7: E111 indentation is not a multiple of four
./tests/test_remove_empty.py:37:7: E111 indentation is not a multiple of four
./tests/test_remove_empty.py:42:7: E111 indentation is not a multiple of four
./tests/test_remove_empty.py:44:7: E111 indentation is not a multiple of four
``

Would you mind fixing the indentation in the new test?

**Comment by JohnReid** [comment]
Sorry I don't know how I missed that one. I think I just trusted it was the same as when I ran flake8 on my machine. Anyway of course I'll fix it.

**Comment by jeff-regier** [comment]
Excellent. Thank you John!

**Comment by JohnReid** [comment]
Thank you for a nice package to work with!

**Pull request merged**
