### PR TITLE
tests : fix matplotlib warnings

### LINKED ISSUE #329: multiprocessing test warnings
```
Traceback (most recent call last):
  File "/home/jeff/miniconda3/lib/python3.7/multiprocessing/semaphore_tracker.py", line 130, in main
    cache.remove(name)
KeyError: b'/loky-4507-1utb25nk'
Traceback (most recent call last):
  File "/home/jeff/miniconda3/lib/python3.7/multiprocessing/semaphore_tracker.py", line 130, in main
    cache.remove(name)
KeyError: b'/loky-4507-m96414k7'
Traceback (most recent call last):
  File "/home/jeff/miniconda3/lib/python3.7/multiprocessing/semaphore_tracker.py", line 130, in main
    cache.remove(name)
KeyError: b'/loky-4507-5i2j6lk2'
```

### LINKED ISSUE #355: tests : matplotlib warnings

### PR DESCRIPTION
**Pull request by gabmis**
fixes `UserWarning: Matplotlib is currently using agg, which is a non-GUI backend` when using tox.
closes #355

### CODE REVIEW

**Comment by jeff-regier** [comment]
#329 was about the key errors. I still see those with this PR. From travis:
```
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/multiprocessing/semaphore_tracker.py", line 130, in main
    cache.remove(name)
KeyError: b'/loky-20201-rexpoa3i'
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/multiprocessing/semaphore_tracker.py", line 130, in main
    cache.remove(name)
KeyError: b'/loky-20201-vdiarstp'
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/multiprocessing/semaphore_tracker.py", line 130, in main
    cache.remove(name)
KeyError: b'/loky-20201-e57zjk2k'
```

**Comment by jeff-regier** [comment]
Oh, it's WIP, got it.

**Comment by gabmis** [comment]
Will fix mutliprocessing `KeyErrors` later - probably when adding the advanced notebook.

**Comment by jeff-regier** [comment]
@PierreBoyeau Looks like Gabriel wants you to look over these changes. Please "squash and merge" once you approve of them.

**Pull request merged**
