### PR TITLE
refresh data_loading notebook and add new content

### LINKED ISSUE #463: `data_loading` tutorial notebook missing path to `TM_droplet_mat.h5ad`
Minor thing: 
When running the tutorial `data_loading notebook`  it couldn't find the dataset `TM_droplet_mat.h5ad`. I solved that by adding a new cell telling it to first download the dataset from the github repo, and then loading it as normal.

```
remote_ann_dataset = DownloadableAnnDataset(
    "TM_droplet_mat.h5ad", 
    save_path=save_path, 
    url='https://github.com/YosefLab/scVI/blob/master/tests/data/TM_droplet_mat.h5ad?raw=true'
)
```
There are the cells in the notebook:
https://github.com/YosefLab/scVI/blob/5fe194d4c30d7a07fa1a4b0a65e057a43262d5de/tests/notebooks/data_loading.ipynb#L200-L231

### LINKED ISSUE #486: Documentation of local 10x loading
It seems to me that the documentation of the Dataset10X function revolves around the use case of downloading one of the pre-defined datasets, and it's not at all clear that this is also the function to use for reading a new user-generated 10x data (presumably a more common scenario). 

Unless I missed something in the docs, I had to look in the code to realize this was the right function to use and what path it was expecting

### PR DESCRIPTION
**Pull request by adamgayoso**
- Fixes #463 
- Fixes #486

### CODE REVIEW

**Comment by adamgayoso** [comment]
I believe I need to add a truncated version of PBMC10k v3.

**Comment by romain-lopez** [comment]
ok I'll wait to review this

**Comment by adamgayoso** [comment]
I added the truncated dataset to #477 so we can merge this after totalVI.

**Comment by romain-lopez** [comment]
Looks good to me, a couple remarks:
+ Is it possible that the last cells were not executed ? 
+ cd../.. again, maybe in another PR.

**Comment by adamgayoso** [comment]
I did not execute the last commands on purpose (memory issues with brain large). They are tested so we know they work. These datasets are also not used by the community at large.

**Pull request merged**
