### PR TITLE
abstract trainer to reduce duplicate code in jvae

### PR DESCRIPTION
**Pull request by adamgayoso**
In the base trainer class I added some helper functions that make it easier to rely on the base train method for more advanced training scenarios - gimVI. I would be also able to use this new code in totalVI.

### CODE REVIEW

**Comment by romain-lopez** [comment]
That looks like a good refactoring to me!

**Comment by romain-lopez** [comment]
@ANazaret does this make sense to you ?

**Comment by ANazaret** [comment]
It looks very good for refactorization!
Just one question: @adamgayoso there will be:
- in_training_loop
- on_training_begin
- on_training_end
- on_iteration_begin
- on_iteration_end
- on_epoch_begin
- on_epoch_end
- training_extras_init
- training_extras_end

Can you detail what is the difference between iteration/epochs/training exactly? Especially iterations/epochs, you could also add a comment in the code to explain.

Thanks

**Comment by adamgayoso** [comment]
Thanks, @ANazaret. I think I made it more clear. Can you review now?

**Comment by ANazaret** [comment]
Great, I understand the difference thank you. 
Maybe just change `in_training_loop`to `on_training_loop` to be consistent with others (the notion of `in` is in `loop`).

**Comment by romain-lopez** [comment]
@adamgayoso should we merge this ?

**Pull request merged**
