### PR TITLE
cache pip for faster travis

### PR DESCRIPTION
**Pull request by adamgayoso**

### CODE REVIEW

**Comment by adamgayoso** [comment]
Ok so pip install requirements is down to 140 secs from ~500 secs. I'm going to go ahead and merge this in.

**Comment by romain-lopez** [comment]
Hi Adam, some questions:
(1) Does it detect changes or do you need to clear the cache manually ?
(2) Do you recommend we stick to testing also the notebook all the time and include all dependencies at install time ? (numba, umap, scanpy etc..) ? 
This will determine which issues to close

**Comment by romain-lopez** [comment]
If this is a reasonable approach, we might want to keep testing the notebooks all the time. Notifying @PierreBoyeau .

**Comment by adamgayoso** [comment]
1) it detects changes to the cache
2) I think we should tests notebooks all the time and figure out the bottlenecks in the notebooks - for example we might have some large datasets in our test data
3) we need to figure out how to unpin every version in requirements.txt

**Comment by romain-lopez** [comment]
solves #434

**Comment by romain-lopez** [comment]
solves #466

**Pull request merged**
