### PR TITLE
Pierre/doc posterior

### LINKED ISSUE #342: One vs all DE bug?
https://github.com/YosefLab/scVI/blob/336aeb0b1566717aea436b6837c48bd162b4d307/scvi/inference/posterior.py#L295

It's hard for me to tell if this is a bug, in particular, I believe `sample_pairs` should be True, otherwise it's not necessary to report permuted Bayes factors in this function. As an aside, it would be great if someone added docstrings to all DE functions :)

### PR DESCRIPTION
**Pull request by PierreBoyeau**
Fixes #342

### CODE REVIEW

**Comment by gabmis** [comment]
Thanks Pierre! While you're at it it would be nice to have parameter annotations using python's `typing`module.  Do you have time to add that before we merge?

@jeff-regier @romain-lopez Is it ok if with review and merge simple PRs ourselves?

**Comment by PierreBoyeau** [comment]
@gabmis Sure thingk!

**Comment by jeff-regier** [comment]
@gabmis Yes, it's fine if whomever you assign to review your PR does the merge. Please use "Squash and merge" so that the whole PR is one commit in master.

**Comment by PierreBoyeau** [comment]
Issue with blame history. I will do a new PR and promise never to use Black again

**Comment by romain-lopez** [comment]
also fixes #317

**Pull request merged**
