### PR TITLE
Finish heat map visualization for differential expression 

### PR DESCRIPTION
**Pull request by imyiningliu**
I added a separate notebook for the heat map. I can remove it to appropriate section if needed.

### CODE REVIEW

**Comment by jeff-regier** [comment]
Let's get PR #91 merged first because we're going to have some merge conflicts here.

**Comment by Edouard360** [comment]
Yes I will take care of merging and solving conflicts.

**Comment by jeff-regier** [comment]
@imyiningliu Yes, probably best to put the heatmap in the main notebook (when you have time...the documentation and wrapping the smfish datasets are more pressing issues).

**Comment by imyiningliu** [comment]
Added heat map for differential expression. 

Added a method to store differential express data as an excel file: 

``gene_names, expression = de_scvi(vae, data_loader, output_file=True)`` 

will returns the ``gene_names`` and ``expression`` data that can be used to plot the heat map, and also store the data as excel spreadsheet.

**Comment by jeff-regier** [comment]
@imyiningliu Would you add an example of how to use this new differential expression plotting to the `docs/notebooks/basic.ipynb` notebook (in the section on differential expression)?

**Comment by jeff-regier** [comment]
@Edouard360 @imyiningliu Can we merge this today? It all look good to me.

**Comment by Edouard360** [comment]
Yes, will do !

**Comment by Edouard360** [comment]
I have rebased:

Last commit message

- add html option to makefile notebook and forward optional notebook name argument
- better integrate differential expression:
  - remove de_cortex function which was too specific, and code duplication
  - differential_expression_stats, differential_expression_score, differential_expression_table methods and bayes_factors function gives the best code factorization while giving all the features that we want ie:
    - just extract the px_scale.
    - get bayes factor for all genes (or a subset) for two cell types populations.
    - extract automatically top 10 differentially expressed genes per cells type.

- Additional
  - add comments for nn_overlap
  - correct uca
  - improve Posterior init

I couldn't install the latex compiler on remote instance so I added a keyword html for jupyter nb convert if that's fine with you jeff. Everything should be in order for this pr now.

**Comment by Edouard360** [comment]
Wait a second before merging something looks wrong let me check

**Comment by Edouard360** [comment]
Can merge !

**Comment by jeff-regier** [comment]
Excellent!

**Pull request merged**
