### PR TITLE
Pierre/fix warnings

### PR DESCRIPTION
**Pull request by PierreBoyeau**
Solution to #327 as the warning made appeared that the case where the lists were empty was not handled properly by `imputation_score`

New test dataset for brain_large is still needed

### CODE REVIEW

**Comment by jeff-regier** [comment]
Looks good to me. Ready to merge?

**Comment by PierreBoyeau** [comment]
Just a second @jeff-regier I did not changed the brain large dataset. 
Once this commit passes travis it should be good !

**Comment by PierreBoyeau** [comment]
Should be ok

**Comment by jeff-regier** [comment]
Thanks Pierre!

**Pull request merged**
